### ISSUE TITLE
Cannot do  make buildimg

### ISSUE THREAD

**Issue by Apoptosis847639** [Absurdponcho/PonchoOS#12]
I was trying to run make buildimg untill this error pop up
![Screenshot 2021-03-22 183629](https://user-images.githubusercontent.com/65559712/112067444-70b3d900-8b3e-11eb-984b-c2d9fb8d720e.png)
Pleas help

**Comment by Tidone** [comment]
Did you somehow customize the Makefile?

According to the picture you are missing at least the following variables:
- OSNAME
- GNUEFI
