### ISSUE TITLE
ALL MODS PLEASE STOP BANNING ME!!!

### ISSUE THREAD

**Issue by byu163** [Absurdponcho/PonchoOS#14]

**Comment by maxdevos49** [comment]
Actions create reactions. Stop banning yourself.

**Comment by nailuj29** [comment]
@byu163 why did you get banned in the first place?

**Comment by nothotscott** [comment]
This is not a GitHub issue. If you want to discuss matters about Discord, then please do so on Discord. @Absurdponcho please close this issue.
