### ISSUE TITLE
Fatal bug in kernelUtil.cpp that runs undetected due to the amount of memory given to QEMU

### ISSUE THREAD

**Issue by rizet** [Absurdponcho/PonchoOS#2]
In kernel/src/kernelUtil.cpp, there is this code:
```c++
    for (uint64_t t = 0; t < GetMemorySize(bootInfo->mMap, mMapEntries, bootInfo->mMapDescSize); t+= 0x1000){
        pageTableManager.MapMemory((void*)t, (void*)t);
    }
```    
which, on 256M of RAM, which is given to QEmu in run.bat, runs perfectly fine.
Yet, allocate 512M of RAM, and the code causes a fatal error. In stock QEMU, this runs in the background, wreaking havoc on the kernel. In QEMU with `accel -kvm`, and most likely real hardware, this error causes a crash.

Please test the code on 512M to see what I mean.

**Comment by RedstonedLife** [comment]
If I'm not mistaken he once ran the code with 2,048M (2 GB) allocated ram.

**Comment by austanss** [comment]
i don't know what i did but it somehow works...

**Comment by neksodebe** [comment]
> i don't know what i did but it somehow works...

BRUH.

**Comment by lapinclown** [comment]
very useful information
