### ISSUE TITLE
Cannot print resolution info in kernel.cpp

### ISSUE THREAD

**Issue by Andrej123456789** [Absurdponcho/PonchoOS#26]
void* BaseAddress;
size_t BufferSize;
unsigned int Width;
unsigned int Height;
unsigned int PixelsPerScanLine;
unsigned int Colour;

This stuff I cannot print in kernel.cpp

**Comment by ilobilo** [comment]
Because they are not strings

**Comment by Andrej123456789** [comment]
How to convert?

**Comment by ilobilo** [comment]
Make int to string function or just watch the series
Poncho does it in one of them

**Comment by Andrej123456789** [comment]
![image](https://user-images.githubusercontent.com/83548580/135746552-05234726-df4b-4ff4-9e13-1f1a7f19c099.png)
![image](https://user-images.githubusercontent.com/83548580/135746557-5254799f-cf84-43f5-9cf2-0455d5075fe8.png)

**Comment by Andrej123456789** [comment]
![image](https://user-images.githubusercontent.com/83548580/135746624-a7d66ae3-c4f5-4dd9-b150-2c6caee59c4b.png)

**Comment by ilobilo** [comment]
That's not ponchos issue. learn c and don't follow tutorials without understanding them

**Comment by Andrej123456789** [comment]
Ilobilo, If you also know C, you would know how to solve this probelm

**Comment by Andrej123456789** [comment]
I fixed with this: 
![image](https://user-images.githubusercontent.com/83548580/135807999-659973a3-03fc-4544-b081-fee34272f029.png)
