### ISSUE TITLE
New Page Map broken

### ISSUE THREAD

**Issue by Andrej123456789** [Absurdponcho/PonchoOS#27]
I finish 8th episode (https://www.youtube.com/watch?v=e47SApmmx44&list=PLxN4E629pPnJxCQCLy7E0SQY_zuumOVyZ&index=8) and Page Map don't work for me:
![image](https://user-images.githubusercontent.com/83548580/138598219-980a464d-e788-45db-bb18-4ee3555e1a39.png)

Code:
![image](https://user-images.githubusercontent.com/83548580/138598226-a9562b19-f952-4b83-9d2a-063030cffc96.png)

Please fix this problem in near future

**Comment by Moldytzu** [comment]
What doesn't work with the page map?

**Comment by Moldytzu** [comment]
Be more precise

**Comment by Moldytzu** [comment]
Does your OS crash or does it do something special?

**Comment by Andrej123456789** [comment]
Nothing crash

**Comment by Andrej123456789** [comment]
I clone PonchoOS and works

**Comment by Andrej123456789** [comment]
Priting text don't work

**Comment by Moldytzu** [comment]
so it crashes

**Comment by Moldytzu** [comment]
![image](https://user-images.githubusercontent.com/40271862/138598556-c272d747-862f-40f2-a2d9-7c960d4127db.png)

**Comment by Moldytzu** [comment]
this is a hint

**Comment by Andrej123456789** [comment]
I have this

**Comment by Moldytzu** [comment]
I already told you where you should look in your code

**Comment by Moldytzu** [comment]
https://media3.giphy.com/media/0owap7cyOBVZO45ZNO/giphy.gif?cid=ecf05e47slxs8asumllxge8nt702pscxel9un1avy9g1k0vk&rid=giphy.gif&ct=g

**Comment by Andrej123456789** [comment]
I copying Poncho code

**Comment by Moldytzu** [comment]
no

**Comment by Moldytzu** [comment]
let me tell you what's the problem

**Comment by Andrej123456789** [comment]
I will keep my modifications

**Comment by Moldytzu** [comment]
you're causing a page fault

**Comment by Moldytzu** [comment]
do you know what is a page fault?

**Comment by Andrej123456789** [comment]
Problem is I cannot print text using new PageMap

**Comment by Moldytzu** [comment]
let me explain to you what's happening ok?

**Comment by Moldytzu** [comment]
you're causing a page fault that's crashing everything

**Comment by Moldytzu** [comment]
do you know what's a page fault?

**Comment by Andrej123456789** [comment]
I watch Poncho episode, create new PageMap like Poncho. Poncho print's text using new PageMa, I cannot print text

**Comment by Moldytzu** [comment]
I asked you something. If you don't listen to me, I won't help you

**Comment by Moldytzu** [comment]
do you know what's a page fault?

**Comment by Moldytzu** [comment]
if not: https://wiki.osdev.org/Exceptions

**Comment by Andrej123456789** [comment]
I don't know where is fault

**Comment by Moldytzu** [comment]
![image](https://user-images.githubusercontent.com/40271862/138598804-1a156a4f-7aaa-4850-a553-e2eaae28218f.png)

**Comment by Moldytzu** [comment]
here

**Comment by Moldytzu** [comment]
A Page Fault occurs when:

    A page directory or table entry is not present in physical memory.
    Attempting to load the instruction TLB with a translation for a non-executable page.
    A protection check (privileges, read/write) failed. <- that's happening now
    A reserved bit in the page directory or table entries is set to 1.

**Comment by Moldytzu** [comment]
you're writing to privileged or inexistent memory

**Comment by Moldytzu** [comment]
if you don't understand what I'm saying let me know

**Comment by Moldytzu** [comment]
wanna tell you the fix?

**Comment by Andrej123456789** [comment]
Whatever you say, I can print now

**Comment by Moldytzu** [comment]
you removed that chunk of code, right?

**Comment by Andrej123456789** [comment]
```

#include <stdint.h>
#include "BasicRenderer.h"
#include "cstr.h"
#include "efiMemory.h"
#include "memory.h"
#include "Bitmap.h"
#include "paging/PageFrameAllocator.h"
#include "paging/PageMapIndexer.h"
#include "paging/paging.h"
#include "paging/PageTableManager.h"

struct BootInfo {
	Framebuffer* framebuffer;
	PSF1_FONT* psf1_Font;
	EFI_MEMORY_DESCRIPTOR* mMap;
	uint64_t mMapSize;
	uint64_t mMapDescSize;
} ;

extern uint64_t _KernelStart;
extern uint64_t _KernelEnd;

extern "C" void _start(BootInfo* bootInfo){
    
    BasicRenderer newRenderer = BasicRenderer(bootInfo->framebuffer, bootInfo->psf1_Font); 

    //Welcome
    newRenderer.Colour = 0xff00ffff;
	newRenderer.CursorPosition = {0, 0};
	newRenderer.Print("Welcome to ringOS!!");
	newRenderer.Print(" ");

	//Basic system info
	newRenderer.Colour = 0xffffff00;

	newRenderer.CursorPosition = {0, 16};
	newRenderer.Print("Basic System Info:");
	newRenderer.Print(" ");

	newRenderer.Print("Width: ");
	newRenderer.Print(to_string((uint64_t)bootInfo->framebuffer->Width));
	newRenderer.Print(" | ");

	newRenderer.Print("Height: ");
	newRenderer.Print(to_string((uint64_t)bootInfo->framebuffer->Height));
	newRenderer.Print(" | ");

	newRenderer.Print("PixelsPerScanLine: ");
	newRenderer.Print(to_string((uint64_t)bootInfo->framebuffer->PixelsPerScanLine));
	newRenderer.Print(" | ");
    
    uint64_t mMapEntries = bootInfo->mMapSize / bootInfo->mMapDescSize;

    GlobalAllocator = PageFrameAllocator();
    GlobalAllocator.ReadEFIMemoryMap(bootInfo->mMap, bootInfo->mMapSize, bootInfo->mMapDescSize);

    uint64_t kernelSize = (uint64_t)&_KernelEnd - (uint64_t)&_KernelStart;
    uint64_t kernelPages = (uint64_t)kernelSize / 4096 + 1;

    GlobalAllocator.LockPages(&_KernelStart, kernelPages);

    PageTable* PML4 = (PageTable*)GlobalAllocator.RequestPage();
    memset(PML4, 0, 0x1000);

    PageTableManager pageTableManager = PageTableManager(PML4);

    for (uint64_t t = 0; t < GetMemorySize(bootInfo->mMap, mMapEntries, bootInfo->mMapDescSize); t+= 0x1000){
        pageTableManager.MapMemory((void*)t, (void*)t);
    }

    uint64_t fbBase = (uint64_t)bootInfo->framebuffer->BaseAddress;
    uint64_t fbSize = (uint64_t)bootInfo->framebuffer->BufferSize + 0x1000;
    for (uint64_t t = fbBase; t < fbBase + fbSize; t += 4096){
        pageTableManager.MapMemory((void*)t, (void*)t);
    }

    asm ("mov %0, %%cr3" : : "r" (PML4));

    pageTableManager.MapMemory((void*)0x600000000, (void*)0x80000);

    uint64_t* test = (uint64_t*)0x600000000;
    *test = 26;

    newRenderer.Print(to_string(*test));
    
    return ;
}
```

**Comment by Andrej123456789** [comment]
My code

**Comment by Moldytzu** [comment]
does it work?

**Comment by Andrej123456789** [comment]
Yes

**Comment by Moldytzu** [comment]
ok

**Comment by Andrej123456789** [comment]
![image](https://user-images.githubusercontent.com/83548580/138598979-19067b4e-c86b-410c-a293-d6ded4c775e4.png)

**Comment by Andrej123456789** [comment]
Thanks for help

**Comment by Moldytzu** [comment]
ur welcome
