### ISSUE TITLE
General Protection Fault / Kernel Panic on Windows 10 Pro

### ISSUE THREAD

**Issue by wmthornton** [Absurdponcho/PonchoOS#31]
When running the image using an unmodified run2.bat on Windows 10 Pro with Qemu installed properly per instructions in video, I receive a General Protection Fault / Kernel Panic everytime. I can run the same image on a Linux machine with zero issues. 

Specs:

Device name	OptiPlex-9020
Processor	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   3.60 GHz
Installed RAM	16.0 GB
Device ID	FF291BCC-D565-4EF1-B5D0-219EDDE6CF04
Product ID	00330-50000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	21H2
Installed on	‎10/‎8/‎2021
OS build	19044.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

Is there some sort of memory addressing issue taking place due to the amount of RAM installed in my system? The Linux machine is a Late-2011 MBP with only 8GB of RAM and Kubuntu 21.04.

Thoughts would be appreciated.

**Comment by Andrej123456789** [comment]
https://github.com/ringwormGO-organization/ringOS#in-emulator

**Comment by Andrej123456789** [comment]
Check this link and give to virual machine enough RAM

**Comment by wmthornton** [comment]
RAM doesn't help - I've assigned 8GB of RAM and no difference.

**Comment by Andrej123456789** [comment]
Add 3GB to Qemu or 4GB to VBOX.

Show some code and try debug your code

**Comment by wmthornton** [comment]
Turns out the code for the run.bat file had a bug that was introduced at some point during development (copy and paste from run.bat instead of run2.bat) - my code uses a file called run.bat so the files were mixed up.
