### ISSUE TITLE
Graphics for this OS

### ISSUE THREAD

**Issue by DolphinFlopFish** [Absurdponcho/PonchoOS#44]
Hello,

I really want to put Graphics in to this but there are no libraries for C++ that support this OS. I want 2d/3d Graphics but I can't get any graphics library that doesn't use Win32 and they also have unrecognized code.

Any help would be great!

**Comment by nothotscott** [comment]
The point of Poncho's tutorials is to write an OS yourself. In the spirit of the series, you should either:

- Write your own graphics library.
- Port an existing graphics library

**Comment by namangor04** [comment]
@nothotscott I agree with you, I am also following this series as i want to learn the basics of writing an OS. Also, [OS-Dev-Wiki](https://wiki.osdev.org/Expanded_Main_Page) is a great place to start with for OS. I already know C/C++, some high level languages too, but just was wondering if to write the whole OS in c/cpp or would it be better to switch to a high-level language after writing the underlying platform specific stuff. Any suggestions and Advice are welcome. :)

**Comment by DolphinFlopFish** [comment]
OK :)

**Comment by DolphinFlopFish** [comment]
I can't find anything, I even looked on the OSDev website, I am not the best coder though in C++.  Anyone have any ways I could put this in to the OS. (Also, will there be anymore tutorials soon?)

**Comment by nothotscott** [comment]
https://wiki.osdev.org/Category:Graphical_UI

You should be at a sufficient level to where you don't need the OS Dev wiki to guide you through what would be your own implementation of a GUI. It's best used might be for architectural-specific stuff like cache policies

**Comment by CorgiMasterEpik** [comment]
You can try to find low level 3d/2d libraries for other operating systems and try to port it to the API of this OS.

This is a smaller then writing your own or porting something like open gl.

Keep in mind none of this will be GPU accelerated unless you ditch UEFI GOP and try to write a GPU driver (like VirtIO for Qemu or an Intel/AMD integrated graphics one)
