### ISSUE TITLE
kernel.cpp:(.text+0x16e): undefined reference to `__stack_chk_fail'

### ISSUE THREAD

**Issue by lapinclown** [Absurdponcho/PonchoOS#50]
After i made my kernel file and other files to C++, i now get this error (yes i installed all dependencies) :
!==== LINKING
ld -T kernel.ld -static -Bsymbolic -nostdlib  -o bin/kernel.elf  lib/BasicRenderer.o  lib/cstr.o  lib/kernel.o
ld: lib/kernel.o: in function `_start':
kernel.cpp:(.text+0x16e): undefined reference to `__stack_chk_fail'
make: *** [Makefile:33: link] Error 1.

**Comment by TheMutta** [comment]
It's a feature that helps you manage stack smashing. There's a nice article on the OSDEV Wiki about that. For now, you can just compile your code with `-fno-stack-protector` to remove the linker warning.

**Comment by Dashbloxx** [comment]
```sudo apt install gcc-multilib```
This may fix your issue.

**Comment by ghost** [comment]
> It's a feature that helps you manage stack smashing. There's a nice article on the OSDEV Wiki about that. For now, you can just compile your code with `-fno-stack-protector` to remove the linker warning.

This is the way to go!
