### ISSUE TITLE
[EP10] QEMU keeps rebooting

### ISSUE THREAD

**Issue by samuelh2005** [Absurdponcho/PonchoOS#7]
it just seems to reboot and nether get to ```Kernel Initialized Successfully``` Probably something with the GDT

**Comment by samuelh2005** [comment]
Is there a way for me to use debug output of QEMU .

**Comment by samuelh2005** [comment]
I've commented out the ```LoadGDT(&gdtDescriptor);``` in the ```kernelUtil.cpp / InitializeKernel``` so it seems like its the ```LoadGDT``` functon

**Comment by samuelh2005** [comment]
@Absurdponcho can you help please if you can?

**Comment by ghost** [comment]
Are you sure your gdt function code is correct? Maybe some mistyped memory addresses?

**Comment by samuelh2005** [comment]
No there correct copied from github but i will sill check

**Comment by samuelh2005** [comment]
It seems like a problem with ```gdt.asm```
```
!==== COMPILING src/gdt/gdt.asm
nasm  src/gdt/gdt.asm -f elf64 -o lib/gdt/gdt_asm.o
src/gdt/gdt.asm:16: warning: symbol `LoadGDT': GLOBAL directive after symbol definition is an experimental feature
src/gdt/gdt.asm:15: warning: label alone on a line without a colon might be in error
```
My nasm version is ```NASM version 2.12.01```

**Comment by ghost** [comment]
The issue might be your makefile not compiling right, but I'm not to sure due to my unfamiliarity with assembly language

**Comment by xubury** [comment]
Heres my gdt.asm, it should get rid of the warnings and compile right. Note: you should change the function name.
```
global loadGDT

section .text
bits 64
loadGDT:
	lgdt [rdi] ;rdi wil be the first parameter
	mov ax, 0x10 ;kernel data segment
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	mov ss, ax
	pop rdi
	mov rax, 0x08 ;kernel code segment
	push rax
	push rdi
	retfq
```

**Comment by samuelh2005** [comment]
Thanks going to try it

**Comment by samuelh2005** [comment]
with the ```retfq``` bit i get
```
!==== COMPILING src/gdt/gdt.asm
nasm  src/gdt/gdt.asm -f elf64 -o lib/gdt/gdt_asm.o
src/gdt/gdt.asm:17: warning: label alone on a line without a colon might be in error
```

**Comment by samuelh2005** [comment]
and my nasm version again ```NASM version 2.12.01```

**Comment by xubury** [comment]
You could try `ret`, but I suspect it will raise other problems.

**Comment by samuelh2005** [comment]
i may try updating qemu

**Comment by samuelh2005** [comment]
its up to date, is there a way to debug it

**Comment by xubury** [comment]
I think you could set up gdb server in qemu. But I've never done that.

**Comment by xubury** [comment]
I did some researches. You can use`O64 retf`instead of `retfq` if `retfq` is not compilied correctly.

**Comment by samuelh2005** [comment]
Messed around with ```kernel/Makefile``` a bit and now 
### It works!

**Comment by ozhanghe** [comment]
What was the fix?

**Comment by GKylian** [comment]
@ajh123 How did you fix it ?

**Comment by le-hachem** [comment]
@ajh123 what was the issue? I am currently stuck at the same issue, and both my nasm and qemu versions are up to date
