### ISSUE TITLE
error with run1.bat: qemu-system-x86_64: failed to find romfile "vgabios-stdvga.bin

### ISSUE THREAD

**Issue by SparksTheFolf** [Absurdponcho/PonchoOS#9]
`set OSNAME=CustomOS
set WORKING_FILE=%0
set FIXED_WORKING_FILE=%WORKING_FILE:"=%
set BUILDDIR=%FIXED_WORKING_FILE%/../bin
set OVMFDIR=%FIXED_WORKING_FILE%/../../OVMFbin

qemu-system-x86_64 -drive "file=%BUILDDIR%/%OSNAME%.img" -m 256M -cpu qemu64 -drive "if=pflash,format=raw,unit=0,file=%OVMFDIR%/OVMF_CODE-pure-efi.fd,readonly=on" -drive "if=pflash,format=raw,unit=1,file=%OVMFDIR%/OVMF_VARS-pure-efi.fd" -net none
pause`
that is what I have for my run1.bat file but when I run it it gives me this error qemu-system-x86_64: failed to find romfile "vgabios-stdvga.bin"

**Comment by Tidone** [comment]
I had the same problem. It looks like qemu is expecting the romfile in the current directory.

To fix that you can either
- Copy the file vgabios-stdvga.bin from your qemu install folder to the kernel folder, or
- Add this to your bat file before the qemu call: `cd /D "C:\Program Files\qemu\"` (Adapt the path to your qemu install folder)

**Comment by SparksTheFolf** [comment]
Awesome Thanks! :)
